INSERT INTO daadi.etiquette (nom) VALUES ('Diagnostics des problèmes technologiques');
INSERT INTO daadi.etiquette (nom) VALUES ('Résolution des problèmes technologiques');
INSERT INTO daadi.etiquette (nom) VALUES ('Problème technique');
INSERT INTO daadi.etiquette (nom) VALUES ('Soutien technique');
INSERT INTO daadi.etiquette (nom) VALUES ('Équipement défectueux');
INSERT INTO daadi.etiquette (nom) VALUES ('Type d''équipement');
INSERT INTO daadi.etiquette (nom) VALUES ('Installation des logiciels et applications');
INSERT INTO daadi.etiquette (nom) VALUES ('Paramétrage des logiciels et applications');
INSERT INTO daadi.etiquette (nom) VALUES ('Paramétrer un logiciel');
INSERT INTO daadi.etiquette (nom) VALUES ('Aide téléphonique');
INSERT INTO daadi.etiquette (nom) VALUES ('Assistance téléphonique');
INSERT INTO daadi.etiquette (nom) VALUES ('Connaissances des fonctionnalités');
INSERT INTO daadi.etiquette (nom) VALUES ('Fonctionnalités de base');
INSERT INTO daadi.etiquette (nom) VALUES ('Documentation institutionnelle');
INSERT INTO daadi.etiquette (nom) VALUES ('Aide à la résolution de problèmes techniques');
INSERT INTO daadi.etiquette (nom) VALUES ('Diversité de méthodes');
INSERT INTO daadi.etiquette (nom) VALUES ('Type de méthodes');
INSERT INTO daadi.etiquette (nom) VALUES ('Activités d''apprentissage individuelles');
INSERT INTO daadi.etiquette (nom) VALUES ('Activités d''apprentissage collaboratives');
INSERT INTO daadi.etiquette (nom) VALUES ('Démonstration');
INSERT INTO daadi.etiquette (nom) VALUES ('Étude de cas');
INSERT INTO daadi.etiquette (nom) VALUES ('Présentations orales');
INSERT INTO daadi.etiquette (nom) VALUES ('Exposés magistraux');
INSERT INTO daadi.etiquette (nom) VALUES ('Carte conceptuelle');
INSERT INTO daadi.etiquette (nom) VALUES ('Jeu de rôle');
INSERT INTO daadi.etiquette (nom) VALUES ('Débat');
INSERT INTO daadi.etiquette (nom) VALUES ('Exercices');
INSERT INTO daadi.etiquette (nom) VALUES ('Tests');
INSERT INTO daadi.etiquette (nom) VALUES ('Quiz');
INSERT INTO daadi.etiquette (nom) VALUES ('Examen');
INSERT INTO daadi.etiquette (nom) VALUES ('Apprentissage par problème');
INSERT INTO daadi.etiquette (nom) VALUES ('Approche par projet');
INSERT INTO daadi.etiquette (nom) VALUES ('Lectures structurées');
INSERT INTO daadi.etiquette (nom) VALUES ('Journal de bord');
INSERT INTO daadi.etiquette (nom) VALUES ('Portfolio');
INSERT INTO daadi.etiquette (nom) VALUES ('Encadrement individualisé');
INSERT INTO daadi.etiquette (nom) VALUES ('Synthèse des savoirs');
INSERT INTO daadi.etiquette (nom) VALUES ('Productions complexes');
INSERT INTO daadi.etiquette (nom) VALUES ('Fonction des apprentissages');
INSERT INTO daadi.etiquette (nom) VALUES ('Évaluation');
INSERT INTO daadi.etiquette (nom) VALUES ('Planification des évaluations');
INSERT INTO daadi.etiquette (nom) VALUES ('Évaluation d''orientation');
INSERT INTO daadi.etiquette (nom) VALUES ('Évaluation de régulation');
INSERT INTO daadi.etiquette (nom) VALUES ('Évaluation de certification');
INSERT INTO daadi.etiquette (nom) VALUES ('Validité');
INSERT INTO daadi.etiquette (nom) VALUES ('Fidélité');
INSERT INTO daadi.etiquette (nom) VALUES ('Tâche complexe');
INSERT INTO daadi.etiquette (nom) VALUES ('Tâche authentique');
INSERT INTO daadi.etiquette (nom) VALUES ('Apprentissage authentique');
INSERT INTO daadi.etiquette (nom) VALUES ('Grille d''évaluation critérée');
INSERT INTO daadi.etiquette (nom) VALUES ('Orientation des apprentissages');
INSERT INTO daadi.etiquette (nom) VALUES ('Évaluation diagnostique');
INSERT INTO daadi.etiquette (nom) VALUES ('Régulation des apprentissages');
INSERT INTO daadi.etiquette (nom) VALUES ('Certification des apprentissages');
INSERT INTO daadi.etiquette (nom) VALUES ('Rétroactions');
INSERT INTO daadi.etiquette (nom) VALUES ('Grille critériée à échelle descriptive');
INSERT INTO daadi.etiquette (nom) VALUES ('Rétroactions automatisées');
INSERT INTO daadi.etiquette (nom) VALUES ('Rétroaction collective');
INSERT INTO daadi.etiquette (nom) VALUES ('Rétroaction individuelle');
INSERT INTO daadi.etiquette (nom) VALUES ('Régulation de l''enseignement');
INSERT INTO daadi.etiquette (nom) VALUES ('Approche pédagogique proactive');
INSERT INTO daadi.etiquette (nom) VALUES ('Approche pédagogique rétroactive');
INSERT INTO daadi.etiquette (nom) VALUES ('Perceptions des personnes étudiantes');
INSERT INTO daadi.etiquette (nom) VALUES ('Planification pédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Calendrier de planification');
INSERT INTO daadi.etiquette (nom) VALUES ('Planifier un cours à distance');
INSERT INTO daadi.etiquette (nom) VALUES ('Séquence d''enseignement');
INSERT INTO daadi.etiquette (nom) VALUES ('Séquence d''activités');
INSERT INTO daadi.etiquette (nom) VALUES ('Articulation théorie');
INSERT INTO daadi.etiquette (nom) VALUES ('Pratique échafaudage');
INSERT INTO daadi.etiquette (nom) VALUES ('Cibles de formation');
INSERT INTO daadi.etiquette (nom) VALUES ('Situation d''apprentissage authentique');
INSERT INTO daadi.etiquette (nom) VALUES ('Obstacle épistémologique');
INSERT INTO daadi.etiquette (nom) VALUES ('Anticiper les difficultés ');
INSERT INTO daadi.etiquette (nom) VALUES ('Obstacle à l''apprentissage');
INSERT INTO daadi.etiquette (nom) VALUES ('Articulation des savoirs');
INSERT INTO daadi.etiquette (nom) VALUES ('Réseau conceptuel des savoirs');
INSERT INTO daadi.etiquette (nom) VALUES ('Savoirs disciplinaires');
INSERT INTO daadi.etiquette (nom) VALUES ('Rôles des personnes formatrices');
INSERT INTO daadi.etiquette (nom) VALUES ('Médiateur du savoir');
INSERT INTO daadi.etiquette (nom) VALUES ('Collaborateur');
INSERT INTO daadi.etiquette (nom) VALUES ('Évaluateur');
INSERT INTO daadi.etiquette (nom) VALUES ('Gestionnaire');
INSERT INTO daadi.etiquette (nom) VALUES ('Accompagnateur');
INSERT INTO daadi.etiquette (nom) VALUES ('Responsabilités des personnes formatrices');
INSERT INTO daadi.etiquette (nom) VALUES ('Cadre pédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Attentes des personnes formatrices');
INSERT INTO daadi.etiquette (nom) VALUES ('Communication ');
INSERT INTO daadi.etiquette (nom) VALUES ('Modalités pédagogiques');
INSERT INTO daadi.etiquette (nom) VALUES ('Mise à l''épreuve épistémologique');
INSERT INTO daadi.etiquette (nom) VALUES ('Alignement technopédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Outils TIC');
INSERT INTO daadi.etiquette (nom) VALUES ('Nature du savoir');
INSERT INTO daadi.etiquette (nom) VALUES ('Potentiel technopédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Médiatisation du contenu');
INSERT INTO daadi.etiquette (nom) VALUES ('Outils externes');
INSERT INTO daadi.etiquette (nom) VALUES ('Outils institutionnels');
INSERT INTO daadi.etiquette (nom) VALUES ('Alignement technoépistémologique');
INSERT INTO daadi.etiquette (nom) VALUES ('Évaluation des outils TIC');
INSERT INTO daadi.etiquette (nom) VALUES ('Usage des outils technologiques en contexte pratique');
INSERT INTO daadi.etiquette (nom) VALUES ('Manipulation');
INSERT INTO daadi.etiquette (nom) VALUES ('Mains sur les touches');
INSERT INTO daadi.etiquette (nom) VALUES ('Alignement technodisciplinaire');
INSERT INTO daadi.etiquette (nom) VALUES ('ENA - Environnement numérique d''apprentissage');
INSERT INTO daadi.etiquette (nom) VALUES ('Moodle');
INSERT INTO daadi.etiquette (nom) VALUES ('Teams');
INSERT INTO daadi.etiquette (nom) VALUES ('Adobe Connect');
INSERT INTO daadi.etiquette (nom) VALUES ('Panopto');
INSERT INTO daadi.etiquette (nom) VALUES ('MonPortfolio');
INSERT INTO daadi.etiquette (nom) VALUES ('Mobilisation d''outils technologiques dans des situations pratiques proprement disciplinaires');
INSERT INTO daadi.etiquette (nom) VALUES ('Structuration des activités d''apprentissage');
INSERT INTO daadi.etiquette (nom) VALUES ('Temps');
INSERT INTO daadi.etiquette (nom) VALUES ('Modules');
INSERT INTO daadi.etiquette (nom) VALUES ('Parcours d''accompagnement');
INSERT INTO daadi.etiquette (nom) VALUES ('Structure de l''ENA');
INSERT INTO daadi.etiquette (nom) VALUES ('Convivialité de l''ENA');
INSERT INTO daadi.etiquette (nom) VALUES ('ENA attrayant');
INSERT INTO daadi.etiquette (nom) VALUES ('Caractéristiques visuelles et graphiques de l''ENA');
INSERT INTO daadi.etiquette (nom) VALUES ('Convivialité des modules d''apprentissage');
INSERT INTO daadi.etiquette (nom) VALUES ('Présentation de l''ENA');
INSERT INTO daadi.etiquette (nom) VALUES ('Fonctionnement de l''ENA');
INSERT INTO daadi.etiquette (nom) VALUES ('Organisation des ressources');
INSERT INTO daadi.etiquette (nom) VALUES ('Aide contextuelle et rappels');
INSERT INTO daadi.etiquette (nom) VALUES ('Rappel');
INSERT INTO daadi.etiquette (nom) VALUES ('Notification');
INSERT INTO daadi.etiquette (nom) VALUES ('Ressources d''aides intégrées');
INSERT INTO daadi.etiquette (nom) VALUES ('Présence enseignante');
INSERT INTO daadi.etiquette (nom) VALUES ('Méthodes de travail');
INSERT INTO daadi.etiquette (nom) VALUES ('Calendrier numérique');
INSERT INTO daadi.etiquette (nom) VALUES ('Ressource organisationnelle');
INSERT INTO daadi.etiquette (nom) VALUES ('Faciliter l''organisation des étudiants');
INSERT INTO daadi.etiquette (nom) VALUES ('Charge de travail');
INSERT INTO daadi.etiquette (nom) VALUES ('Contexte de formation');
INSERT INTO daadi.etiquette (nom) VALUES ('Méthodes d''enseignement synchrones');
INSERT INTO daadi.etiquette (nom) VALUES ('Modalités d''enseignement');
INSERT INTO daadi.etiquette (nom) VALUES ('Animation des séances');
INSERT INTO daadi.etiquette (nom) VALUES ('Méthodes d''enseignement asynchrones');
INSERT INTO daadi.etiquette (nom) VALUES ('Classe inversée');
INSERT INTO daadi.etiquette (nom) VALUES ('Méthodes pédagogiques collaboratives');
INSERT INTO daadi.etiquette (nom) VALUES ('Méthoodes pédagogiques expositives');
INSERT INTO daadi.etiquette (nom) VALUES ('Méthodes pédagogiques individuelles');
INSERT INTO daadi.etiquette (nom) VALUES ('Méthode d''évaluation intégrant les TIC');
INSERT INTO daadi.etiquette (nom) VALUES ('Orientattion des apprentissages intégrant les TIC');
INSERT INTO daadi.etiquette (nom) VALUES ('Outils d''évaluation');
INSERT INTO daadi.etiquette (nom) VALUES ('Examens à distance');
INSERT INTO daadi.etiquette (nom) VALUES ('Modalités de rétroaction');
INSERT INTO daadi.etiquette (nom) VALUES ('Rétroaction audio/video/écrite');
INSERT INTO daadi.etiquette (nom) VALUES ('Moments de rétroaction');
INSERT INTO daadi.etiquette (nom) VALUES ('Pérennisation des ressources pédagogiues numériques');
INSERT INTO daadi.etiquette (nom) VALUES ('Conception du matériel');
INSERT INTO daadi.etiquette (nom) VALUES ('Portée des interventions pédagogiques asynchrones');
INSERT INTO daadi.etiquette (nom) VALUES ('Fréquence des interventions pédagogiques asynchrones');
INSERT INTO daadi.etiquette (nom) VALUES ('Sentiment d''isolement');
INSERT INTO daadi.etiquette (nom) VALUES ('Articulation des activités d''apprentissage synchrone');
INSERT INTO daadi.etiquette (nom) VALUES ('Articulation des activités d''apprentissage asynchrone');
INSERT INTO daadi.etiquette (nom) VALUES ('Fonction des activités d''apprentissage');
INSERT INTO daadi.etiquette (nom) VALUES ('Intention de communication associée aux outils');
INSERT INTO daadi.etiquette (nom) VALUES ('Modalités de communication');
INSERT INTO daadi.etiquette (nom) VALUES ('Facilitation des interactions asynchrones');
INSERT INTO daadi.etiquette (nom) VALUES ('Facilitation des interactions synchrones');
INSERT INTO daadi.etiquette (nom) VALUES ('Clarté des consignes');
INSERT INTO daadi.etiquette (nom) VALUES ('Interactivités');
INSERT INTO daadi.etiquette (nom) VALUES ('Interactions et situations de communication');
INSERT INTO daadi.etiquette (nom) VALUES ('Facilitateur');
INSERT INTO daadi.etiquette (nom) VALUES ('Flexibilité pédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Fréquence des interventions via l''ENA');
INSERT INTO daadi.etiquette (nom) VALUES ('Stratégies de communication avec les personnes étudiantes');
INSERT INTO daadi.etiquette (nom) VALUES ('Attentes mutuelles');
INSERT INTO daadi.etiquette (nom) VALUES ('Bienséance en ligne');
INSERT INTO daadi.etiquette (nom) VALUES ('Engagement');
INSERT INTO daadi.etiquette (nom) VALUES ('Suivi de la participation');
INSERT INTO daadi.etiquette (nom) VALUES ('Établissement de la relation pédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Entretien de la relation pédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Planification didactique');
INSERT INTO daadi.etiquette (nom) VALUES ('Échafaudage');
INSERT INTO daadi.etiquette (nom) VALUES ('Planification pédagogique échafaudée');
INSERT INTO daadi.etiquette (nom) VALUES ('Organiser le contenu disciplinaire');
INSERT INTO daadi.etiquette (nom) VALUES ('Posture épistémologique disciplinaire');
INSERT INTO daadi.etiquette (nom) VALUES ('Articulation du contenu disciplinaire');
INSERT INTO daadi.etiquette (nom) VALUES ('Construction du savoir disciplinaire');
INSERT INTO daadi.etiquette (nom) VALUES ('Illustrations disciplinaires');
INSERT INTO daadi.etiquette (nom) VALUES ('Contenus de formation');
INSERT INTO daadi.etiquette (nom) VALUES ('Situations authentiques');
INSERT INTO daadi.etiquette (nom) VALUES ('Plan de cours');
INSERT INTO daadi.etiquette (nom) VALUES ('Approches pédagogiques différenciées');
INSERT INTO daadi.etiquette (nom) VALUES ('Mise à jour de ressources');
INSERT INTO daadi.etiquette (nom) VALUES ('Mise à jour pédagogique/disciplinaire');
INSERT INTO daadi.etiquette (nom) VALUES ('Veille pédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Interventions pédagogiques proactive');
INSERT INTO daadi.etiquette (nom) VALUES ('Interventions pédagogiques rétroactives');
INSERT INTO daadi.etiquette (nom) VALUES ('Anticiper les obstacles');
INSERT INTO daadi.etiquette (nom) VALUES ('Documenter les obstacles');
INSERT INTO daadi.etiquette (nom) VALUES ('Niveau d''autonomie');
INSERT INTO daadi.etiquette (nom) VALUES ('Différenciation pédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Mise à niveau');
INSERT INTO daadi.etiquette (nom) VALUES ('Identifier les défis cognitifs');
INSERT INTO daadi.etiquette (nom) VALUES ('Étapes du processus d''apprentissage');
INSERT INTO daadi.etiquette (nom) VALUES ('Fil conducteur du cours');
INSERT INTO daadi.etiquette (nom) VALUES ('Accompagnement pédagogique');
INSERT INTO daadi.etiquette (nom) VALUES ('Bon contexte de formation');
INSERT INTO daadi.etiquette (nom) VALUES ('Pertinence/ adaptation des méthodes');
INSERT INTO daadi.etiquette (nom) VALUES ('Comparaison théorie/pratique');
INSERT INTO daadi.etiquette (nom) VALUES ('Préférences technopédagogiques');
INSERT INTO daadi.etiquette (nom) VALUES ('Alignement technopédago-épistémologique');
INSERT INTO daadi.etiquette (nom) VALUES ('Méthodes technopédagogiques adaptées aux cibles de formation ou champ disciplinaire');
INSERT INTO daadi.etiquette (nom) VALUES ('Outils technologiques liés au champ disciplinaire');
INSERT INTO daadi.etiquette (nom) VALUES ('À déterminer');